# Generated by Django 6.0.4 on 2026-05-06 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('admin_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('under_review', 'In valutazione'), ('negotiation', 'In trattativa'), ('offer_accepted', 'Offerta accettata'), ('waiting_vinted_link', 'In attesa link Vinted'), ('vinted_link_sent', 'Link Vinted inviato'), ('completed', 'Completato'), ('rejected', 'Rifiutato')], default='under_review', max_length=30)),
                ('vinted_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proposals/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proposals.itemproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='proposals.itemproposal')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
