# Generated by Django 6.0.4 on 2026-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproposal',
            name='status',
            field=models.CharField(choices=[('under_review', 'In valutazione'), ('negotiation', 'In trattativa'), ('offer_sent', 'Offerta inviata'), ('offer_accepted', 'Offerta accettata'), ('waiting_vinted_link', 'In attesa link Vinted'), ('vinted_link_sent', 'Link Vinted inviato'), ('completed', 'Completato'), ('rejected', 'Rifiutato')], default='under_review', max_length=30),
        ),
    ]
