# Generated by Django 6.0.4 on 2026-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_itemproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproposal',
            name='offer_seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
