# Generated by Django 6.0.4 on 2026-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_itemproposal_offer_seen_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmessage',
            name='seen_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposalmessage',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
