# Generated by Django 6.0.4 on 2026-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposalmessage_seen_by_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproposal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemproposal',
            name='negotiation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemproposal',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemproposal',
            name='offer_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemproposal',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemproposal',
            name='vinted_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
