# Generated by Django 6.0.4 on 2026-07-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_itemproposal_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproposal',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='itemproposal',
            name='negotiation_at',
        ),
        migrations.RemoveField(
            model_name='itemproposal',
            name='offer_accepted_at',
        ),
        migrations.RemoveField(
            model_name='itemproposal',
            name='offer_sent_at',
        ),
        migrations.RemoveField(
            model_name='itemproposal',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='itemproposal',
            name='vinted_link_sent_at',
        ),
        migrations.CreateModel(
            name='ProposalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Proposta inviata'), ('negotiation', 'Messa in trattativa'), ('offer_sent', 'Offerta inviata'), ('offer_accepted', 'Offerta accettata'), ('waiting_vinted_link', 'In attesa del link Vinted'), ('vinted_link_sent', 'Link Vinted inviato'), ('completed', 'Proposta completata'), ('rejected', 'Proposta rifiutata')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proposals.itemproposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
