# Generated by Django 6.0.4 on 2026-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_remove_itemproposal_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproposal',
            name='status',
            field=models.CharField(choices=[('under_review', 'In valutazione'), ('negotiation', 'In trattativa'), ('offer_sent', 'Offerta inviata'), ('offer_accepted', 'Offerta accettata'), ('vinted_link_sent', 'Link Vinted inviato'), ('completed', 'Completato'), ('rejected', 'Rifiutato')], default='under_review', max_length=30),
        ),
        migrations.AlterField(
            model_name='proposalevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Proposta inviata'), ('negotiation', 'Messa in trattativa'), ('offer_sent', 'Offerta inviata'), ('offer_accepted', 'Offerta accettata'), ('vinted_link_sent', 'Link Vinted inviato'), ('completed', 'Proposta completata'), ('rejected', 'Proposta rifiutata')], max_length=30),
        ),
    ]
